# Configuracion del Servidor
server.port=8080
spring.application.name=clima-api-externa

# Configuracion de API Externa de Clima (Open-Meteo - Gratuita y sin API Key obligatoria)
clima.external.open-meteo.base-url=https://api.open-meteo.com/v1/forecast
clima.external.open-meteo.geocoding-url=https://geocoding-api.open-meteo.com/v1/search

# Configuracion de OpenWeatherMap (Opcional si se dispone de API Key)
clima.external.openweathermap.base-url=https://api.openweathermap.org/data/2.5
clima.external.openweathermap.api-key=

# Timeouts para RestTemplate (en milisegundos)
clima.http.connect-timeout=6000
clima.http.read-timeout=6000

# Parametros de simulacion de WhatsApp Business Cloud API (Meta)
whatsapp.cloud-api.base-url=https://graph.facebook.com/v19.0
whatsapp.cloud-api.phone-number-id=109283748291039
whatsapp.cloud-api.access-token=EAAB...SIMULATED_TOKEN...XYZ
