# Archivo de configuración de Spring Boot, en este archivo se definen las propiedades de la aplicación,
# como la configuración de la base de datos, el puerto del servidor, entre otros.
# La conexión a la base de datos se realiza a través de JDBC, y se especifica el dialecto de Hibernate para MariaDB. Se usa
# SQL workbench para crear la base de datos demo_abm y se debe crear un usuario con permisos para acceder a la base de datos
# de manera local. Se recomienda usar el usuario root con contraseña root para fines de desarrollo y pruebas. Para una implementación
# en producción, se debe crear un usuario con permisos limitados y una contraseña segura. La persistencia se genera de forma local
# es decir, no se sube a la nube, por lo que no es necesario configurar un servidor de base de datos en la nube.
# Se recomienda usar MySQL Workbench para administrar la base de datos de manera local.

spring.application.name=demo

# Configuración de base de datos MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/demo_abm?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect