# Ruta a la base de datos SQLite (se crear\u00e1 autom\u00e1ticamente en la ra\u00edz si no existe)
spring.datasource.url=jdbc:sqlite:midatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Muestra en consola las consultas SQL ejecutadas por Spring
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
spring.sql.init.mode=always
