package org.example.entity;

import java.util.List;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "products", indexes = @Index(name = "idx_product_name", columnList = "name"))
@Getter
@Setter
public class Product {
    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Identifier generated by DB
    private Long id;
    private String name;
    private double price;
    private int stock;
    @ManyToMany(mappedBy = "products")
    private List<Category> categories;
    @OneToMany(mappedBy = "product")
    private List<SaleDetail> saleDetails;
}
