spring.datasource.url=jdbc:sqlite:./videojuegos.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=never

#Variable de entorno
server.port=9000

#Imagenes
spring.servlet.multipart.max-file-size=15MB
app.upload-dir=./uploads
